"""Added is_atomic_column

Revision ID: 2799a0d940a0
Revises: e79518fa376d
Create Date: 2021-05-14 11:34:07.419743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2799a0d940a0'
down_revision = 'e79518fa376d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('is_atomic', sa.Boolean(), nullable=False, server_default="TRUE"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'is_atomic')
    # ### end Alembic commands ###
