"""added completed_lesson flag to lesson model

Revision ID: 4a01c2fc77a6
Revises: 2799a0d940a0
Create Date: 2021-05-14 23:21:12.089372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a01c2fc77a6'
down_revision = '2799a0d940a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_completion', sa.Column('completed_lesson', sa.Boolean(), nullable=False, server_default="FALSE"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_completion', 'completed_lesson')
    # ### end Alembic commands ###
