"""Renamed lesson model

Revision ID: e79518fa376d
Revises: cbeb3c0d7df4
Create Date: 2021-04-26 15:59:44.200071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79518fa376d'
down_revision = 'cbeb3c0d7df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_completion',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('progression', sa.Integer(), nullable=False),
    sa.Column('completed_test', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user', 'lesson_id')
    )
    op.drop_table('lesson')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('user', sa.INTEGER(), nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.Column('progression', sa.INTEGER(), nullable=False),
    sa.Column('completed_test', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user', 'lesson_id')
    )
    op.drop_table('lesson_completion')
    # ### end Alembic commands ###
