"""empty message

Revision ID: ec884f3bd806
Revises: 4a01c2fc77a6
Create Date: 2021-05-16 11:17:10.453450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec884f3bd806'
down_revision = '4a01c2fc77a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('puzzle_completion', sa.Column('test_number', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'puzzle_completion', 'test', ['test_number'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'puzzle_completion', type_='foreignkey')
    op.drop_column('puzzle_completion', 'test_number')
    op.drop_table('test')
    # ### end Alembic commands ###
